language: python

python:
  - 3.6

install:
  - sudo apt-get install -y python3-pyaudio libportaudio2
  - pip install coveralls
  - pip install .

script:
  - python setup.py test
  - coverage run -m doctest gensound/**/*.py

after_success:
  - coveralls
