language: python

python:
  - 3.5
  - 3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y portaudio19-dev libsndfile1
  - pip install coveralls
  - pip install pep8

install:
  - pip install .

script:
  - coverage run setup.py test

after_success:
  - coveralls
